version: "3"

services:
  minio_image:
    image: minio/minio
    container_name: minio_image
    restart: unless-stopped
    volumes:
      - /app/minio/images:/images
      # - /app/minio/certs1:${HOME}/.minio/certs
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /images

  minio_file:
    image: minio/minio
    container_name: minio_file
    restart: unless-stopped
    volumes:
      - /app/minio/files:/files
      # - /app/minio/certs1:${HOME}/.minio/certs
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /files

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on: 
      - minio_image
      - minio_file
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
      - "82:82"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
